# Tabuada
n = int(input('Digite um valor numérico inteiro: '))
print('{}x1 = {}'.format(n, n*1))
print('{}x2 = {}'.format(n, n*2))
print('{}x3 = {}'.format(n, n*3))
print('{}x4 = {}'.format(n, n*4))
print('{}x5 = {}'.format(n, n*5))
print('{}x6 = {}'.format(n, n*6))
print('{}x7 = {}'.format(n, n*7))
print('{}x8 = {}'.format(n, n*8))
print('{}x9 = {}'.format(n, n*9))
print('{}x10= {}'.format(n, n*10))
